[package]
name = "my-ai-assistant-project"
version = "0.1.0"
edition = "2018"

[dependencies]
google-cloud-speech = "0.10.0"
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
